<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ATMECSINLT-404" name="com.atmecs.falcon_testing_excel.falcon_excel_demo.testscript.LoginTest" tests="1" failures="0" timestamp="02 Dec 2020 06:00:38 GMT" time="0.011" errors="1">
  <testcase name="testLogin" time="0.011" classname="com.atmecs.falcon_testing_excel.falcon_excel_demo.testscript.LoginTest">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: testLogin([Parameter{index=0, type=com.atmecs.falcon_testing_excel.falcon_excel_demo.pages.HTUser, declaredAnnotations=[]}])
Arguments: [(java.lang.String) nithya,(java.lang.String) ni1234]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: testLogin([Parameter{index=0, type=com.atmecs.falcon_testing_excel.falcon_excel_demo.pages.HTUser, declaredAnnotations=[]}])
Arguments: [(java.lang.String) nithya,(java.lang.String) ni1234]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.atmecs.falcon_testing_excel.falcon_excel_demo.runner.TestNGRunner.main(TestNGRunner.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testLogin -->
</testsuite> <!-- com.atmecs.falcon_testing_excel.falcon_excel_demo.testscript.LoginTest -->
